[build]
builder = "nixpacks"
buildCommand = "cd license-backend && npm install"

[deploy]
startCommand = "cd license-backend && npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

